### PR TITLE
Added AddInstutions Page

### PR DESCRIPTION
**Pull request by kiridharan**
image

Review and Update the change .

### CODE REVIEW

**Comment by kiridharan** [comment]
@smartclash Some vercel deployment Error please check it .

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Brittle

**Comment by smartclash** [comment]
Good one, but create an `institution` folder inside `admin` folder and have all the `create.tsx` and `view.tsx` files there.

**Review by smartclash — CHANGES_REQUESTED** [review]
Let us follow the same naming structure everywhere. It should be `create.tsx` for any form page and `view.tsx` for listing all the items.

**Comment by kiridharan** [comment]
image

Bro Finished View Institutions page as well check and update any change 

Todo:
1. improve Styling  

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by kiridharan** [comment]
> Let us follow the same naming structure everywhere. It should be `create.tsx` for any form page and `view.tsx` for listing all the items.

I did fix .

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by kiridharan** [comment]
image
image

Changed design and and Added volunteer feature .
@smartclash Hope it is okay now__

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by kiridharan** [comment]
Institution create
image
Volunteer create
image

**Pull request merged**
