### PR TITLE
Events Page

### PR DESCRIPTION
**Pull request by kiridharan**

### CODE REVIEW

**Comment by smartclash** [comment]
Use containers and cards to make the form look good. Use this as reference

https://github.com/smartclash/SIH-Frontend/blob/8c2572156f65c70bc23fba977e3cd90e484ac090/pages/admin/dashboard.tsx#L53-L55

**Comment by kiridharan** [comment]
image


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by kiridharan** [comment]
image


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by smartclash** [comment]
Instead of this file name

```
├── pages
│   ├── events
│   │   ├── addevents.tsx
│   │   └── viewEvents.tsx
```

rename the files to this

```
├── pages
│   ├── events
│   │   ├── create.tsx
│   │   └── view.tsx
```

**Comment by kiridharan** [comment]
Rename File Done

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Pull request merged**
